INSERT INTO business_unit (BUSINESS_CD,BUSINESS_DESC,BUSINESS_UNIT_NAME,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('BU-BANK','Banking related domain','BU-BANK',1,0,0,null,null,'A');
INSERT INTO business_unit (BUSINESS_CD,BUSINESS_DESC,BUSINESS_UNIT_NAME,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('BU-COMMERCE','Banking commerece','BU-BANK',1,0,0,null,null,'A');
INSERT INTO business_unit (BUSINESS_CD,BUSINESS_DESC,BUSINESS_UNIT_NAME,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('BU-TELE','Banking telecommunication','BU-BANK',1,0,0,null,null,'A');


INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 1 of BU-BANK','PROJ_1_BU_BANK',1,1,0,0,null,null,'A');
INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 2 of BU-BANK','PROJ_2_BU_BANK',1,1,0,0,null,null,'A');
INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 3 of BU-BANK','PROJ_3_BU_BANK',1,1,0,0,null,null,'A');
INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 1 of BU-COMMERCE','PROJ_1_BU_COMM',1,2,0,0,null,null,'A');
INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 2 of BU-COMMERCE','PROJ_2_BU_COMM',1,2,0,0,null,null,'A');
INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 3 of BU-COMMERCE','PROJ_3_BU_COMM',1,2,0,0,null,null,'A');

INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Software','Java',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Telecommunication','Telnet',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('HR related','Excel',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Risk assessment','FRM',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Software','C++',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Scrum','Analytics',1,0,0,null,null,'A');