INSERT INTO company_mstr (COMPANY_NAME,COMPANY_CD,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('LNT Infotech','LTI_CD',0,0,null,null,'A');
INSERT INTO business_unit (BUSINESS_CD,BUSINESS_DESC,BUSINESS_UNIT_NAME,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('BU-BANK','Banking related domain','BU-BANK',1,0,0,null,null,'A');

INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 1 of BU-BANK','PROJ_1_BU_BANK',1,1,0,0,null,null,'A');
INSERT INTO project (PROJECT_DESC,PROJECT_NAME,COMPANY_MSTR_SEQ,BUSINESS_UNIT_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Proect 2 of BU-BANK','PROJ_2_BU_BANK',1,1,0,0,null,null,'A');

INSERT INTO project_item (PROJECT_SEQ,PROJECT_ITEM_DESC,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (1,'Project item one',0,0,null,null,'A');
INSERT INTO project_item (PROJECT_SEQ,PROJECT_ITEM_DESC,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (2,'Project item four',0,0,null,null,'A');


INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Software','Java',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Telecommunication','Telnet',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('HR related','Excel',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Software','C++',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Document','Word Doc',1,0,0,null,null,'A');
INSERT INTO skill_mstr (SKILL_DOMAIN,SKILL_DESC,COMPANY_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('Printing','Printer',1,0,0,null,null,'A');


INSERT INTO project_item_skill (PROJECT_ITEM_SEQ,SKILL_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (1,1,0,0,null,null,'A');
INSERT INTO project_item_skill (PROJECT_ITEM_SEQ,SKILL_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (1,2,0,0,null,null,'A');
INSERT INTO project_item_skill (PROJECT_ITEM_SEQ,SKILL_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (1,3,0,0,null,null,'A');

INSERT INTO project_item_skill (PROJECT_ITEM_SEQ,SKILL_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (2,4,0,0,null,null,'A');
INSERT INTO project_item_skill (PROJECT_ITEM_SEQ,SKILL_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (2,5,0,0,null,null,'A');
INSERT INTO project_item_skill (PROJECT_ITEM_SEQ,SKILL_MSTR_SEQ,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES (2,6,0,0,null,null,'A');