INSERT INTO company_mstr (COMPANY_NAME,COMPANY_CD,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) VALUES ('LNT Infotech','LTI_CD',0,0,null,null,'A');

INSERT INTO user_role (COMPANY_MSTR_SEQ,USER_ROLE_DESC,USER_ROLE_CD,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) values (1,'Project Manager in company','ROLE_EMPLOYEE',0,0,null,null,'A');

INSERT INTO user_profile(USER_ROLE_SEQ,COMPANY_MSTR_SEQ,USER_ID,PASSWORD,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE,STATUS) values (1,1,'user_id','$2a$10$45dDLeCNcVX9UFzJbC1.n.StkPPX5d2R4O.W/e9wiD705QPP.6Z.C',0,0,null,null,'A');